# Generated by Django 4.1.3 on 2022-12-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_show_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
