# Generated by Django 4.1.3 on 2022-12-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_film_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
