# Generated by Django 4.1.3 on 2022-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_banner_film_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='date_added',
        ),
        migrations.AddField(
            model_name='banner',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
