# Generated by Django 4.1.3 on 2022-12-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_film_movie_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='movie_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.film'),
        ),
    ]
