# Generated by Django 4.1.3 on 2022-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_rename_movie_name_banner_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie_lang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Language'),
        ),
    ]
