# Generated by Django 4.1.3 on 2022-12-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_film_movie_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.film', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Banner Image URL'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_name',
            field=models.CharField(max_length=100, verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_plot',
            field=models.TextField(blank=True, help_text='movie plot here ', null=True, verbose_name='Plot'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='show',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.film', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Ticket Price'),
        ),
        migrations.AlterField(
            model_name='show',
            name='showtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Showtime'),
        ),
        migrations.AlterField(
            model_name='show',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
