# Generated by Django 4.1.3 on 2022-12-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_num_seats_alter_booking_seat_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(null=True),
        ),
    ]
