# Generated by Django 4.1.3 on 2022-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
