# Generated by Django 4.1.3 on 2022-12-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_show_date_alter_booking_booked_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
